language: python
python:
  - "2.6"
  - "2.7"
env:
#  - DJANGO=1.3.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
#  - DJANGO=https://github.com/django/django/zipball/master
install:
#  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r schedule/requirements.txt --use-mirrors
  - pip install -e . --use-mirrors
  - pip install coveralls
script:
  - python setup.py develop
  - python schedule/manage.py syncdb --noinput
  - python schedule/manage.py migrate schedule
  - python schedule/manage.py loaddata schedule
  - coverage run --source=schedule schedule/manage.py test
after_success:
  - coveralls
